// auth/service.ts — register, login, verify email, reset password.

import argon2 from "argon2";
import { z } from "zod";

import { prisma } from "../lib/prisma";
import {
  BadRequestError,
  ConflictError,
  UnauthorizedError,
} from "../lib/errors";
import { setSessionUser } from "../lib/auth-context";


// ----- Validation schemas (re-exported for use by API routes) ------------------

export const RegisterSchema = z.object({
  email: z.string().email().max(255),
  password: z.string()
    .min(8)
    .regex(/[A-Z]/, "must include an uppercase letter")
    .regex(/[a-z]/, "must include a lowercase letter")
    .regex(/[0-9]/, "must include a digit"),
  displayName: z.string().min(2).max(64),
});

export const LoginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(1),
});


// ----- Public API --------------------------------------------------------------

export async function register(input: z.infer<typeof RegisterSchema>) {
  const data = RegisterSchema.parse(input);
  const existing = await prisma.user.findUnique({ where: { email: data.email } });
  if (existing) throw new ConflictError("An account with this email already exists");

  const passwordHash = await argon2.hash(data.password, { type: argon2.argon2id });
  const user = await prisma.user.create({
    data: {
      email: data.email,
      displayName: data.displayName,
      passwordHash,
      // status starts as PENDING_VERIFICATION; an email verification token
      // is generated by a separate flow (not shown — owner #1).
    },
  });

  return { id: user.id, email: user.email };
}

export async function login(input: z.infer<typeof LoginSchema>) {
  const data = LoginSchema.parse(input);
  const user = await prisma.user.findUnique({ where: { email: data.email } });
  // Constant-time-ish: always run argon2 verify with a fixed dummy hash to
  // make timing of "user not found" indistinguishable from "wrong password".
  const dummy = "$argon2id$v=19$m=65536,t=3,p=4$AAAAAAAAAAAAAAAAAAAAAA$AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
  const ok = await argon2.verify(user?.passwordHash ?? dummy, data.password)
                 .catch(() => false);
  if (!user || !ok) throw new UnauthorizedError("Invalid email or password");

  if (user.status === "SUSPENDED")
    throw new UnauthorizedError("Account suspended");
  if (user.status === "DELETED")
    throw new UnauthorizedError("Account deleted");
  if (user.status === "PENDING_VERIFICATION")
    throw new UnauthorizedError("Please verify your email first");

  await setSessionUser(user.id);
  return { id: user.id, email: user.email, displayName: user.displayName };
}

export async function changePassword(userId: string, oldPassword: string, newPassword: string) {
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user) throw new UnauthorizedError();
  const ok = await argon2.verify(user.passwordHash, oldPassword);
  if (!ok) throw new UnauthorizedError("Current password is wrong");
  if (newPassword.length < 8) throw new BadRequestError("New password too short");
  const newHash = await argon2.hash(newPassword, { type: argon2.argon2id });
  await prisma.user.update({ where: { id: userId }, data: { passwordHash: newHash } });
}
