"use client";
import { useEffect, useState } from "react";
import { ReportButton } from "@/components/moderation/ReportButton";
type Msg = { id: string; body: string; createdAt: string; sender: { id: string; displayName: string } };
export function ChatThread({ conversationId, currentUserId }: { conversationId: string; currentUserId: string }) { const [messages, setMessages] = useState<Msg[]>([]); const [body, setBody] = useState(""); const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch(`/api/conversations/${conversationId}/messages`).then(r => r.json()).then(out => setMessages(out.messages ?? [])).catch(() => setError("Could not load messages")); const source = new EventSource(`/api/conversations/${conversationId}/stream`); source.addEventListener("message", event => { const msg = JSON.parse((event as MessageEvent).data) as Msg; setMessages(current => current.some(row => row.id === msg.id) ? current : [...current, msg]); }); return () => source.close(); }, [conversationId]);
  async function send(e: React.FormEvent) { e.preventDefault(); const res = await fetch(`/api/conversations/${conversationId}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body }) }); const out = await res.json().catch(() => ({})); if (!res.ok) { setError(out.error ?? "Send failed"); return; } setMessages(current => [...current, out]); setBody(""); }
  return <div className="space-y-3"><div className="max-h-[60vh] space-y-2 overflow-y-auto rounded border p-3">{messages.map(message => <div key={message.id} className={`rounded p-2 ${message.sender.id === currentUserId ? "ml-10 bg-blue-100 text-black" : "mr-10 bg-gray-100 text-black"}`}><p className="text-xs font-semibold">{message.sender.displayName}</p><p>{message.body}</p><p className="text-xs text-gray-500">{new Date(message.createdAt).toLocaleString()}</p>{message.sender.id !== currentUserId && <ReportButton targetType="MESSAGE" targetId={message.id} />}</div>)}</div><form onSubmit={send} className="flex gap-2"><input required value={body} onChange={e => setBody(e.target.value)} className="flex-1 rounded border px-2 py-1" placeholder="Write a message"/><button className="rounded bg-blue-600 px-3 py-2 text-white">Send</button></form>{error && <p className="text-sm text-red-600">{error}</p>}</div>;
}
